(define (problem rcll-prod-c0-prob1)
	(:domain rcll-prod-c0)

	(:objects
		R-1 R-2 R-3 - robot
		o1 - order
		wp1 - workpiece
		cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)
	 
	(:init
	 (mps-type C-BS BS)
	 (mps-type C-CS1 CS)
	 (mps-type C-CS1 CS)
	 (mps-type C-DS DS)
	 (mps-type C-RS1 RS)
	 (mps-type C-RS2 RS)
	 (location-free START ANYSIDE)
	 (location-free C-BS INPUT)
	 (location-free C-BS OUTPUT)
	 (location-free C-CS1 INPUT)
	 (location-free C-CS1 OUTPUT)
	 (location-free C-CS2 INPUT)
	 (location-free C-CS2 OUTPUT)
	 (location-free C-DS INPUT)
	 (location-free C-DS OUTPUT)
	 ;(location-free C-RS1 INPUT)
	 ;(location-free C-RS1 OUTPUT)
	 ;(location-free C-RS2 INPUT)
	 ;(location-free C-RS2 OUTPUT)
	 (location-allowed C-BS)
	 (location-allowed C-CS1)
	 (location-allowed C-CS2)
	 (location-allowed C-DS)
	 ;(location-allowed C-RS1)
	 ;(location-allowed C-RS2)
	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
	 (robot-waiting R-1)
	 (robot-waiting R-2)
	 (robot-waiting R-3)
	 (mps-state C-BS IDLE)
 	 (mps-state C-CS1 IDLE)
 	 (mps-state C-CS2 IDLE)
	 (mps-state C-DS IDLE)
 	 (mps-state C-RS1 IDLE)
 	 (mps-state C-RS2 IDLE)

   ; (rs-ring-spec C-RS1 RING_GREEN)
   ; (rs-ring-spec C-RS1 RING_ORANGE)
   ; (rs-ring-spec C-RS2 RING_BLUE)
   ; (rs-ring-spec C-RS2 RING_YELLOW)

   (wp-base-color cb1 BASE_CC)
   ;(wp-base-color cb2 BASE_CC)
   ;(wp-base-color cb3 BASE_CC)
   (wp-cap-color cb1 CAP_BLACK)
   ;(wp-cap-color cb2 CAP_BLACK)
   ;(wp-cap-color cb3 CAP_BLACK)
   (wp-on-shelf cb1 C-CS2 LEFT)
   ;(wp-on-shelf cb2 C-CS2 MIDDLE)
   ;(wp-on-shelf cb3 C-CS2 RIGHT)

	 (order-complexity o1 c0)
	 (order-base-color o1 BASE_BLACK)
	 (order-cap-color o1 CAP_BLACK)
	)

	(:goal (order-fulfilled o1) )
)
